---
## Example AWS WAF rule set covering generic OWASP Top 10 vulnerability
## areas with PHP backend specific misconfigurations.
##
## Copyright 2016 Amazon.com, Inc. or its affiliates. All Rights Reserved.
## Licensed under the Amazon Software License (the "License"). You may not use this file except in compliance with the License.
## A copy of the License is located at http://aws.amazon.com/asl/ or in the "license" file accompanying this file.
## This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, express or implied.
## See the License for the specific language governing permissions and limitations under the License.
##
## Changelog:
## 2017-06-27 - Initial release
##
## Repository:
## https://github.com/awslabs/aws-waf-sample
##
## Dependencies:
## none

AWSTemplateFormatVersion: '2010-09-09'
Description: AWS WAF Basic OWASP Example Rule Set

## ::PARAMETERS::
## Template parameters to be configured by user
## ::RESOURCES::
## Resources used in this solution
Resources:
## 1.
## OWASP Top 10 A1
## Mitigate SQL Injection Attacks
## Matches attempted SQLi patterns in the URI, QUERY_STRING, BODY, COOKIES
  wafgSQLiSet:
    Type: AWS::WAF::SqlInjectionMatchSet
    Properties:
      Name: generical-detect-sqli
      SqlInjectionMatchTuples:
        - FieldToMatch:
            Type: URI
          TextTransformation: URL_DECODE
        - FieldToMatch:
            Type: URI
          TextTransformation: HTML_ENTITY_DECODE
        - FieldToMatch:
            Type: QUERY_STRING
          TextTransformation: URL_DECODE
        - FieldToMatch:
            Type: QUERY_STRING
          TextTransformation: HTML_ENTITY_DECODE
        - FieldToMatch:
            Type: BODY
          TextTransformation: URL_DECODE
        - FieldToMatch:
            Type: BODY
          TextTransformation: HTML_ENTITY_DECODE
        - FieldToMatch:
            Type: HEADER
            Data: cookie
          TextTransformation: URL_DECODE
        - FieldToMatch:
            Type: HEADER
            Data: cookie
          TextTransformation: HTML_ENTITY_DECODE
  wafgSQLiRule:
    Type: AWS::WAF::Rule
    Properties:
      MetricName: genericaclmitigatesqli
      Name: generical-mitigate-sqli
      Predicates:
        - Type: SqlInjectionMatch
          Negated: false
          DataId: !Ref wafgSQLiSet

## 2.
## OWASP Top 10 A2
## Blacklist bad/hijacked JWT tokens or session IDs
## Matches the specific values in the cookie or Authorization header
## for JWT it is sufficient to check the signature
  wafgAuthTokenStringSet:
    Type: AWS::WAF::ByteMatchSet
    Properties:
      Name: generical-match-auth-tokens
      ByteMatchTuples:
        - FieldToMatch:
            Type: HEADER
            Data: cookie
          PositionalConstraint: CONTAINS
          TargetString: example-session-id
          TextTransformation: URL_DECODE
        - FieldToMatch:
            Type: HEADER
            Data: authorization
          PositionalConstraint: ENDS_WITH
          TargetString: .TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
          TextTransformation: URL_DECODE
  wafgAuthTokenRule:
    Type: AWS::WAF::Rule
    Properties:
      MetricName: genericaclbadauthtokens
      Name: generical-detect-bad-auth-tokens
      Predicates:
        - Type: ByteMatch
          Negated: false
          DataId: !Ref wafgAuthTokenStringSet


## 3.
## OWASP Top 10 A3
## Mitigate Cross Site Scripting Attacks
## Matches attempted XSS patterns in the URI, QUERY_STRING, BODY, COOKIES
  wafgXSSSet:
    Type: AWS::WAF::XssMatchSet
    Properties:
      Name: generical-detect-xss
      XssMatchTuples:
        - FieldToMatch:
            Type: URI
          TextTransformation: URL_DECODE
        - FieldToMatch:
            Type: URI
          TextTransformation: HTML_ENTITY_DECODE
        - FieldToMatch:
            Type: QUERY_STRING
          TextTransformation: URL_DECODE
        - FieldToMatch:
            Type: QUERY_STRING
          TextTransformation: HTML_ENTITY_DECODE
        - FieldToMatch:
            Type: BODY
          TextTransformation: URL_DECODE
        - FieldToMatch:
            Type: BODY
          TextTransformation: HTML_ENTITY_DECODE
        - FieldToMatch:
            Type: HEADER
            Data: cookie
          TextTransformation: URL_DECODE
        - FieldToMatch:
            Type: HEADER
            Data: cookie
          TextTransformation: HTML_ENTITY_DECODE
  wafgXSSRule:
    Type: AWS::WAF::Rule
    Properties:
      MetricName: genericaclmitigatexss
      Name: generical-mitigate-xss
      Predicates:
        - Type: XssMatch
          Negated: false
          DataId: !Ref wafgXSSSet

## 4.
## OWASP Top 10 A4
## Path Traversal, LFI, RFI
## Matches request patterns designed to traverse filesystem paths, and include
## local or remote files

  wafgPathsStringSet:
    Type: AWS::WAF::ByteMatchSet
    Properties:
      Name: generical-match-rfi-lfi-traversal
      ByteMatchTuples:
        - FieldToMatch:
            Type: URI
          PositionalConstraint: CONTAINS
          TargetString: ../
          TextTransformation: URL_DECODE
        - FieldToMatch:
            Type: URI
          PositionalConstraint: CONTAINS
          TargetString: ../
          TextTransformation: HTML_ENTITY_DECODE
        - FieldToMatch:
            Type: QUERY_STRING
          PositionalConstraint: CONTAINS
          TargetString: ../
          TextTransformation: URL_DECODE
        - FieldToMatch:
            Type: QUERY_STRING
          PositionalConstraint: CONTAINS
          TargetString: ../
          TextTransformation: HTML_ENTITY_DECODE
        - FieldToMatch:
            Type: URI
          PositionalConstraint: CONTAINS
          TargetString: ://
          TextTransformation: URL_DECODE
        - FieldToMatch:
            Type: URI
          PositionalConstraint: CONTAINS
          TargetString: ://
          TextTransformation: HTML_ENTITY_DECODE
        - FieldToMatch:
            Type: QUERY_STRING
          PositionalConstraint: CONTAINS
          TargetString: ://
          TextTransformation: URL_DECODE
        - FieldToMatch:
            Type: QUERY_STRING
          PositionalConstraint: CONTAINS
          TargetString: ://
          TextTransformation: HTML_ENTITY_DECODE
  wafgPathsRule:
    Type: AWS::WAF::Rule

    Properties:
      MetricName: genericacldetectrfilfi
      Name: generical-detect-rfi-lfi-traversal
      Predicates:
        - Type: ByteMatch
          Negated: false
          DataId: !Ref wafgPathsStringSet

## 5.
## OWASP Top 10 A4
## Privileged Module Access Restrictions
## Restrict access to the admin interface to known source IPs only
## Matches the URI prefix, when the remote IP isn't in the whitelist
  wafgAdminUrlStringSet:
    Type: AWS::WAF::ByteMatchSet
    Properties:
      Name: generical-match-admin-url
      ByteMatchTuples:
        - FieldToMatch:
            Type: URI
          PositionalConstraint: STARTS_WITH
          TargetString: /admin
          TextTransformation: URL_DECODE
  wafgAdminRemoteAddrIpSet:
    Type: AWS::WAF::IPSet
    Properties:
      Name: generical-match-admin-remote-ip
      IPSetDescriptors:
        - Type: IPV4
          Value: 127.0.0.1/32
  wafgAdminAccessRule:
    Type: AWS::WAF::Rule
    Properties:
      MetricName: genericacldetectadminaccess
      Name: generical-detect-admin-access
      Predicates:
        - Type: ByteMatch
          Negated: false
          DataId: !Ref wafgAdminUrlStringSet
        - Type: IPMatch
          Negated: true
          DataId: !Ref wafgAdminRemoteAddrIpSet

## 6.
## OWASP Top 10 A5
## PHP Specific Security Misconfigurations
## Matches request patterns designed to exploit insecure PHP/CGI configuration
  wafgPHPInsecureQSStringSet:
    Type: AWS::WAF::ByteMatchSet
    Properties:
      Name: generical-match-php-insecure-var-refs
      ByteMatchTuples:
        - FieldToMatch:
            Type: QUERY_STRING
          PositionalConstraint: CONTAINS
          TargetString: _SERVER[
          TextTransformation: URL_DECODE
        - FieldToMatch:
            Type: QUERY_STRING
          PositionalConstraint: CONTAINS
          TargetString: _ENV[
          TextTransformation: URL_DECODE
        - FieldToMatch:
            Type: QUERY_STRING
          PositionalConstraint: CONTAINS
          TargetString: auto_prepend_file=
          TextTransformation: URL_DECODE
        - FieldToMatch:
            Type: QUERY_STRING
          PositionalConstraint: CONTAINS
          TargetString: auto_append_file=
          TextTransformation: URL_DECODE
        - FieldToMatch:
            Type: QUERY_STRING
          PositionalConstraint: CONTAINS
          TargetString: allow_url_include=
          TextTransformation: URL_DECODE
        - FieldToMatch:
            Type: QUERY_STRING
          PositionalConstraint: CONTAINS
          TargetString: disable_functions=
          TextTransformation: URL_DECODE
        - FieldToMatch:
            Type: QUERY_STRING
          PositionalConstraint: CONTAINS
          TargetString: open_basedir=
          TextTransformation: URL_DECODE
        - FieldToMatch:
            Type: QUERY_STRING
          PositionalConstraint: CONTAINS
          TargetString: safe_mode=
          TextTransformation: URL_DECODE
  wafgPHPInsecureURIStringSet:
    Type: AWS::WAF::ByteMatchSet
    Properties:
      Name: generical-match-php-insecure-uri
      ByteMatchTuples:
        - FieldToMatch:
            Type: URI
          PositionalConstraint: ENDS_WITH
          TargetString: php
          TextTransformation: URL_DECODE
        - FieldToMatch:
            Type: URI
          PositionalConstraint: ENDS_WITH
          TargetString: /
          TextTransformation: URL_DECODE
  wafgPHPInsecureRule:
    Type: AWS::WAF::Rule
    Properties:
      MetricName: genericacldetectphpinsecure
      Name: generical-detect-php-insecure
      Predicates:
        - Type: ByteMatch
          Negated: false
          DataId: !Ref wafgPHPInsecureQSStringSet
        - Type: ByteMatch
          Negated: false
          DataId: !Ref wafgPHPInsecureURIStringSet

## 7.
## OWASP Top 10 A7
## Mitigate abnormal requests via size restrictions
## Enforce consistent request hygene, limit size of key elements
  wafgSizeRestrictionSet:
    Type: AWS::WAF::SizeConstraintSet
    Properties:
      Name: generical-size-restrictions
      SizeConstraints:
        - FieldToMatch:
            Type: URI
          TextTransformation: NONE
          ComparisonOperator: GT
          Size: 512
        - FieldToMatch:
            Type: QUERY_STRING
          TextTransformation: NONE
          ComparisonOperator: GT
          Size: 1024
        - FieldToMatch:
            Type: BODY
          TextTransformation: NONE
          ComparisonOperator: GT
          Size: 4096
        - FieldToMatch:
            Type: HEADER
            Data: cookie
          TextTransformation: NONE
          ComparisonOperator: GT
          Size: 4093
  wafgSizeRestrictionRule:
    Type: AWS::WAF::Rule
    Properties:
      MetricName: genericaclrestrictsizes
      Name: generical-restrict-sizes
      Predicates:
        - Type: SizeConstraint
          Negated: false
          DataId: !Ref wafgSizeRestrictionSet

## 8.
## OWASP Top 10 A8
## CSRF token enforcement example
## Enforce the presence of CSRF token in request header
  wafgCSRFMethodStringSet:
    Type: AWS::WAF::ByteMatchSet
    Properties:
      Name: generical-match-csrf-method
      ByteMatchTuples:
        - FieldToMatch:
            Type: METHOD
          PositionalConstraint: EXACTLY
          TargetString: post
          TextTransformation: LOWERCASE
  wafgCSRFTokenSizeConstraint:
    Type: AWS::WAF::SizeConstraintSet
    Properties:
      Name: generical-match-csrf-token
      SizeConstraints:
        - FieldToMatch:
            Type: HEADER
            Data: x-csrf-token
          TextTransformation: NONE
          ComparisonOperator: EQ
          Size: 36
  wafgCSRFRule:
    Type: AWS::WAF::Rule
    Properties:
      MetricName: genericaclenforcecsrf
      Name: generical-enforce-csrf
      Predicates:
        - Type: ByteMatch
          Negated: false
          DataId: !Ref wafgCSRFMethodStringSet
        - Type: SizeConstraint
          Negated: true
          DataId: !Ref wafgCSRFTokenSizeConstraint

## 9.
## OWASP Top 10 A9
## Server-side includes & libraries in webroot
## Matches request patterns for webroot objects that shouldn't be directly accessible
  wafgServerSideIncludeStringSet:
    Type: AWS::WAF::ByteMatchSet
    Properties:
      Name: generical-match-ssi
      ByteMatchTuples:
        - FieldToMatch:
            Type: URI
          PositionalConstraint: STARTS_WITH
          TargetString: /includes
          TextTransformation: URL_DECODE
        - FieldToMatch:
            Type: URI
          PositionalConstraint: ENDS_WITH
          TargetString: .cfg
          TextTransformation: LOWERCASE
        - FieldToMatch:
            Type: URI
          PositionalConstraint: ENDS_WITH
          TargetString: .conf
          TextTransformation: LOWERCASE
        - FieldToMatch:
            Type: URI
          PositionalConstraint: ENDS_WITH
          TargetString: .config
          TextTransformation: LOWERCASE
        - FieldToMatch:
            Type: URI
          PositionalConstraint: ENDS_WITH
          TargetString: .ini
          TextTransformation: LOWERCASE
        - FieldToMatch:
            Type: URI
          PositionalConstraint: ENDS_WITH
          TargetString: .log
          TextTransformation: LOWERCASE
        - FieldToMatch:
            Type: URI
          PositionalConstraint: ENDS_WITH
          TargetString: .bak
          TextTransformation: LOWERCASE
        - FieldToMatch:
            Type: URI
          PositionalConstraint: ENDS_WITH
          TargetString: .backup
          TextTransformation: LOWERCASE
  wafgServerSideIncludeRule:
    Type: AWS::WAF::Rule
    Properties:
      MetricName: genericacldetectssi
      Name: generical-detect-ssi
      Predicates:
        - Type: ByteMatch
          Negated: false
          DataId: !Ref wafgServerSideIncludeStringSet

## 10.
## Generic
## IP Blacklist
## Matches IP addresses that should not be allowed to access content
  wafgBlacklistIpSet:
    Type: AWS::WAF::IPSet
    Properties:
      Name: generical-match-blacklisted-ips
      IPSetDescriptors:
        - Type: IPV4
          Value: 10.0.0.0/8
        - Type: IPV4
          Value: 192.168.0.0/16
        - Type: IPV4
          Value: 169.254.0.0/16
        - Type: IPV4
          Value: 172.16.0.0/16
        - Type: IPV4
          Value: 127.0.0.1/32
  wafgBlacklistIpRule:
    Type: AWS::WAF::Rule
    Properties:
      MetricName: genericaclblacklistedips
      Name: generical-detect-blacklisted-ips
      Predicates:
        - Type: IPMatch
          Negated: false
          DataId: !Ref wafgBlacklistIpSet

## --
## WebACL containing the above rules evaluated in-order
  wafgOwaspACL:
    Type: AWS::WAF::WebACL
    Properties:
      MetricName: genericaclowaspacl
      Name: generical-owasp-acl
      DefaultAction:
        Type: ALLOW
      Rules:
        - Action:
            Type: COUNT
          Priority: 10
          RuleId: !Ref wafgSizeRestrictionRule
        - Action:
            Type: COUNT
          Priority: 20
          RuleId: !Ref wafgBlacklistIpRule
        - Action:
            Type: COUNT
          Priority: 30
          RuleId: !Ref wafgAuthTokenRule
        - Action:
            Type: COUNT
          Priority: 40
          RuleId: !Ref wafgSQLiRule
        - Action:
            Type: COUNT
          Priority: 50
          RuleId: !Ref wafgXSSRule
        - Action:
            Type: COUNT
          Priority: 60
          RuleId: !Ref wafgPathsRule
        - Action:
            Type: COUNT
          Priority: 70
          RuleId: !Ref wafgPHPInsecureRule
        - Action:
            Type: COUNT
          Priority: 80
          RuleId: !Ref wafgCSRFRule
        - Action:
            Type: COUNT
          Priority: 90
          RuleId: !Ref wafgServerSideIncludeRule
        - Action:
            Type: COUNT
          Priority: 100
          RuleId: !Ref wafgAdminAccessRule

